// <auto-generated />
using System;
using LocadoraVeiculos.API.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocadoraVeiculos.API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260920221719_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevistaDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantidadeDiarias")
                        .HasColumnType("int");

                    b.Property<int?>("QuilometragemFinal")
                        .HasColumnType("int");

                    b.Property<int>("QuilometragemInicial")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Aluguel");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Aluguel_ClienteId");

                    b.HasIndex("DataRetirada")
                        .HasDatabaseName("IX_Aluguel_DataRetirada");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("IX_Aluguel_VeiculoId");

                    b.ToTable("Aluguel", null, t =>
                        {
                            t.HasCheckConstraint("CK_Aluguel_Periodo", "[DataPrevistaDevolucao] >= [DataRetirada]");

                            t.HasCheckConstraint("CK_Aluguel_Quilometragem", "[QuilometragemFinal] IS NULL OR [QuilometragemFinal] >= [QuilometragemInicial]");

                            t.HasCheckConstraint("CK_Aluguel_ValorDiaria", "[ValorDiaria] > 0");

                            t.HasCheckConstraint("CK_Aluguel_ValorTotal", "[ValorTotal] >= 0");
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("ValorDiariaSugerido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Categoria");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categoria_Nome");

                    b.ToTable("Categoria", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categoria_ValorDiariaSugerido", "[ValorDiariaSugerido] >= 0");
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroCnh")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Cliente");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("UQ_Cliente_Cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Cliente_Email");

                    b.ToTable("Cliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cliente_Cpf_11Digitos", "LEN([Cpf]) = 11");
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoFundacao")
                        .HasColumnType("int")
                        .HasColumnName("AnoFundacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Nome");

                    b.Property<string>("PaisOrigem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("PaisOrigem");

                    b.HasKey("Id")
                        .HasName("PK_Fabricante");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UQ_Fabricante_Nome");

                    b.ToTable("Fabricante", (string)null);
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Filial");

                    b.HasIndex("Cidade", "Nome")
                        .HasDatabaseName("IX_Filial_Cidade_Nome");

                    b.ToTable("Filial", (string)null);
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AluguelId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoTransacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Pagamento");

                    b.HasIndex("AluguelId");

                    b.ToTable("Pagamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamento_Valor", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<int>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<int?>("FilialId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("NumeroPassageiros")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDiaria")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id")
                        .HasName("PK_Veiculo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("FilialId");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("UQ_Veiculo_Placa");

                    b.ToTable("Veiculo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Veiculo_AnoFabricacao", "[AnoFabricacao] >= 1900");

                            t.HasCheckConstraint("CK_Veiculo_Quilometragem", "[Quilometragem] >= 0");

                            t.HasCheckConstraint("CK_Veiculo_ValorDiaria", "[ValorDiaria] > 0");
                        });
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Aluguel", b =>
                {
                    b.HasOne("LocadoraVeiculos.API.Modelos.Cliente", "Cliente")
                        .WithMany("Alugueis")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Aluguel_Cliente");

                    b.HasOne("LocadoraVeiculos.API.Modelos.Veiculo", "Veiculo")
                        .WithMany("Alugueis")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Aluguel_Veiculo");

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Pagamento", b =>
                {
                    b.HasOne("LocadoraVeiculos.API.Modelos.Aluguel", "Aluguel")
                        .WithMany("Pagamentos")
                        .HasForeignKey("AluguelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pagamento_Aluguel");

                    b.Navigation("Aluguel");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Veiculo", b =>
                {
                    b.HasOne("LocadoraVeiculos.API.Modelos.Categoria", "Categoria")
                        .WithMany("Veiculos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Veiculo_Categoria");

                    b.HasOne("LocadoraVeiculos.API.Modelos.Fabricante", "Fabricante")
                        .WithMany("Veiculos")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Veiculo_Fabricante");

                    b.HasOne("LocadoraVeiculos.API.Modelos.Filial", "Filial")
                        .WithMany("Veiculos")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Veiculo_Filial");

                    b.Navigation("Categoria");

                    b.Navigation("Fabricante");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Aluguel", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Categoria", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Cliente", b =>
                {
                    b.Navigation("Alugueis");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Fabricante", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Filial", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("LocadoraVeiculos.API.Modelos.Veiculo", b =>
                {
                    b.Navigation("Alugueis");
                });
#pragma warning restore 612, 618
        }
    }
}
